# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod properties
mod_version=2.6.0
maven_group=net.witcher_class
archives_name=witcher-class-mod
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.1

# Dependencies
fabric_loader_version = 0.17.3
fabric_api_version = 0.116.7+1.21.1
neoforge_version = 21.1.209
yarn_mappings_patch_neoforge_version = 1.21+build.4
forgified_fabric_api_version=0.115.6+2.1.1+1.21.1
fabric_version=0.115.6+1.21.1
cloth_config_version=15.0.130
player_anim_version=2.0.0-alpha1+1.21
spell_power_version=1.4.0+1.21.1
tiny_config_version=3.0.0
mixin_extras_version=0.1.1
azure_mc_version=1.21.1
azure_lib_version=3.0.1
spell_engine_version=1.8.2+1.21.1
more_rpg_library_version=2.5.0+1.21.1

# Fabric only
trinkets_version=3.10.0
mod_menu_version=11.0.2

# NeoForge only
owo_version=0.12.15.4+1.21
owo_neo_version=0.12.15.5-beta.1+1.21
accessories_version=1.1.0-beta.48+1.21.1